########################################################################################
#                                                                                      #
#      WAVIN AHC-9000 FLOOR HEATING CONTROLLER SOFTWARE FOR HOME ASSISTANT             #
#                                                                                      #   
#        Code developed by : Heine Koldbro Madsen and Samuel Sieb 2021                 #
#                                                                                      #
# https://github.com/heinekmadsen/esphome_components/tree/main/components/wavinAhc9000 #    
#                                                                                      #
# Hardware by : Mogens Groth Nicolaisen https://github.com/nic6911/Wavin-AHC-9000-mqtt #                                                                                       #
#                                                                                      #
########################################################################################


########################################################################################
#                      CONFIGURATION PART OF YOUR CHOICE :)                            #
########################################################################################

substitutions:
  device_name: 'wavin'
  friendly_name: 'Wavin'
  log_level: DEBUG
 
  # UPDATE TIME (GATEWAY)
  update_interval: 60s
  
  # CHANNEL ID´S
  channel_1:  Bryggers
  channel_2:  Bjarnes Kontor
  channel_3:  Køkken
  channel_4:  Spise område
  channel_5:  Stue Kreds 1
  channel_6:  Stue Kreds 2
  channel_7:  Soveværelse
  channel_8:  Badeværelse
  channel_9:  Walkin Closet
  channel_10: Daisys Kontor
  channel_11: Gæsteværelse
  channel_12: Entre
  channel_13: Gæstebadeværelse
  channel_14: <Unused>
  channel_15: <Unused>
  channel_16: <Unused>
  
  # TEMP STEP + CLIMATE MIN/MAX LIMIT TEMP SETPOINT
  temp_step:   '0.5'
  climate_min_temp: '12'  
  climate_max_temp: '40'
  
  # PIN DEFINITIONS (Should in most cases not be changed) 
  tx_enable_pin: '2'
  rx_pin: RX
  tx_pin: TX

  # WiFi settings
  ssid_set: !secret wifi_ssid
  password_set: !secret wifi_password
   
########################################################################################
#                        CODE BELOW SHOULD NOT BE CHANGED                              #
########################################################################################  

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m
  project:
    name: "home.wavin_gulvvarme"
    version: "1.0.0"

# Enable logging
logger:
  baud_rate: 0
    
# Enable Home Assistant API
api:
  
ota:
  password: "945ac67ddcae11048f6a488672b6aadb"

wifi:
  ssid: ${ssid_set}
  password: ${password_set}
  manual_ip:
    static_ip: 192.168.1.203
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wavin Fallback Hotspot"
    password: "12345678"

captive_portal:  

uart:
  rx_pin: ${rx_pin}
  tx_pin: ${tx_pin}
  baud_rate: 38400
  id: uart_modbus
  stop_bits: 1
  
external_components:
  - source: github://heinekmadsen/esphome_components

# Temporary fix for modbus component error in ESPHome 2021.10.0
# https://github.com/esphome/issues/issues/2630
# Might not be nessesary in future builds, but for now it is
#  - source:
#      type: git
#      url: https://github.com/martgras/esphome
#      ref: modbus-fix
#    components: [ modbus ]
  
modbus:
  uart_id: uart_modbus

web_server:
  version: 2
  
wavinAhc9000:
  update_interval: ${update_interval}
  rw_pin: ${tx_enable_pin}
  
climate:
  - platform: wavinAhc9000
    channel: 1
    name: ${friendly_name} Climate ${channel_1}
    current_temp:
      name: ${friendly_name} Temp ${channel_1}
    visual:
      temperature_step: ${temp_step} °C
      min_temperature: ${climate_min_temp} °C
      max_temperature: ${climate_max_temp} °C
      
  - platform: wavinAhc9000
    channel: 2
    name: ${friendly_name} Climate ${channel_2}
    current_temp:
      name: ${friendly_name} Temp ${channel_2}
    visual:
      temperature_step: ${temp_step} °C
      min_temperature: ${climate_min_temp} °C
      max_temperature: ${climate_max_temp} °C
      
  - platform: wavinAhc9000
    channel: 3
    name: ${friendly_name} Climate ${channel_3}
    current_temp:
      name: ${friendly_name} Temp ${channel_3}
    visual:
      temperature_step: ${temp_step} °C
      min_temperature: ${climate_min_temp} °C
      max_temperature: ${climate_max_temp} °C
      
  - platform: wavinAhc9000
    channel: 4
    name: ${friendly_name} Climate ${channel_4}
    current_temp:
      name: ${friendly_name} Temp ${channel_4}
    visual:
      temperature_step: ${temp_step} °C
      min_temperature: ${climate_min_temp} °C
      max_temperature: ${climate_max_temp} °C
      
  - platform: wavinAhc9000
    channel: 5
    name: ${friendly_name} Climate ${channel_5}
    current_temp:
      name: ${friendly_name} Temp ${channel_5}
    visual:
      temperature_step: ${temp_step} °C
      min_temperature: ${climate_min_temp} °C
      max_temperature: ${climate_max_temp} °C
      
  - platform: wavinAhc9000
    channel: 6
    name: ${friendly_name} Climate ${channel_6}
    current_temp:
      name: ${friendly_name} Temp ${channel_6}
    visual:
      temperature_step: ${temp_step} °C
      min_temperature: ${climate_min_temp} °C
      max_temperature: ${climate_max_temp} °C
      
  - platform: wavinAhc9000
    channel: 7
    name: ${friendly_name} Climate ${channel_7}
    current_temp:
      name: ${friendly_name} Temp ${channel_7}
    visual:
      temperature_step: ${temp_step} °C
      min_temperature: ${climate_min_temp} °C
      max_temperature: ${climate_max_temp} °C
      
  - platform: wavinAhc9000
    channel: 8
    name: ${friendly_name} Climate ${channel_8}
    current_temp:
      name: ${friendly_name} Temp ${channel_8}
    visual:
      temperature_step: ${temp_step} °C
      min_temperature: ${climate_min_temp} °C
      max_temperature: ${climate_max_temp} °C
      
  - platform: wavinAhc9000
    channel: 9
    name: ${friendly_name} Climate ${channel_9}
    current_temp:
      name: ${friendly_name} Temp ${channel_9}
    visual:
      temperature_step: ${temp_step} °C
      min_temperature: ${climate_min_temp} °C
      max_temperature: ${climate_max_temp} °C
      
  - platform: wavinAhc9000
    channel: 10
    name: ${friendly_name} Climate ${channel_10}
    current_temp:
      name: ${friendly_name} Temp ${channel_10}
    visual:
      temperature_step: ${temp_step} °C
      min_temperature: ${climate_min_temp} °C
      max_temperature: ${climate_max_temp} °C
      
  - platform: wavinAhc9000
    channel: 11
    name: ${friendly_name} Climate ${channel_11}
    current_temp:
      name: ${friendly_name} Temp ${channel_11}       
    visual:
      temperature_step: ${temp_step} °C
      min_temperature: ${climate_min_temp} °C
      max_temperature: ${climate_max_temp} °C
      
  - platform: wavinAhc9000
    channel: 12
    name: ${friendly_name} Climate ${channel_12}
    current_temp:
      name: ${friendly_name} Temp ${channel_12}       
    visual:
      temperature_step: ${temp_step} °C
      min_temperature: ${climate_min_temp} °C
      max_temperature: ${climate_max_temp} °C
      
  - platform: wavinAhc9000
    channel: 13
    name: ${friendly_name} Climate ${channel_13}
    current_temp:
      name: ${friendly_name} Temp ${channel_13}       
    visual:
      temperature_step: ${temp_step} °C
      min_temperature: ${climate_min_temp} °C
      max_temperature: ${climate_max_temp} °C
      
     
