substitutions:
  # UNIQUE NAME FOR THE DEVICE
  device: wavin # Case sensitive!!!
  name: Wavin   # "Friendly name" - not case sensitive!!!

  # WiFi settings
  ssid_set: !secret wifi_ssid
  password_set: !secret wifi_password
  
  # CHANNEL friendly names (If using spaces remember to add ")
  channel_01_friendly_name:  "Bryggers"
  channel_02_friendly_name:  "Bjarnes Kontor"
  channel_03_friendly_name:  "Køkken"
#  channel_04_friendly_name:  "Spise område"
  channel_05_friendly_name:  "Stue"
#  channel_06_friendly_name:  "Stue Kreds 2"
  channel_07_friendly_name:  "Soveværelse"
  channel_08_friendly_name:  "Badeværelse"
  channel_09_friendly_name:  "Walkin"
  channel_10_friendly_name: "Daisys Kontor"
  channel_11_friendly_name: "Gæsteværelse"
#  channel_12_friendly_name: "Entre"
  channel_13_friendly_name: "Gæstebadeværelse"
  channel_14_friendly_name: "<Unused>"
  channel_15_friendly_name: "<Unused>"
  channel_16_friendly_name: "<Unused>"
  
  # CHANNEL ID´S (ONLY LOWER CASE LETTERS, NO SPACES) used for entity ids
  channel_01_id: utility_room
  channel_02_id: office_bjarne
  channel_03_id: kitchen
#  channel_04_id: dining_area
  channel_05_id: living_room_1
#  channel_06_id: living_room_2
  channel_07_id: bedroom
  channel_08_id: bathroom
  channel_09_id: walkin_closet
  channel_10_id: office_daisy
  channel_11_id: guest_room
#  channel_12_id: hallway
  channel_13_id: guest_bathroom

esphome:
  name: wavin

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "YjS64FUUM+WlQx647hKSSsjZ2ARR3n3ra5mhfYKxuxY="

ota:
  password: "288b4f30b095a3a0b18a087da7eb8bbc"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wavin Fallback Hotspot"
    password: "cm0WFDxdtDY3"

captive_portal:

packages:
  remote_package:
    url: https://github.com/briis/esphome
    ref: main
    files: 
      - components/wavin/basic.yaml # REQUIRED FOR WAVIN AHC 9000
      - components/wavin/channel_01.yaml
      - components/wavin/channel_02.yaml
      - components/wavin/channel_03.yaml
#      - components/wavin/channel_04.yaml
      - components/wavin/channel_05.yaml
#      - components/wavin/channel_06.yaml
      - components/wavin/channel_07.yaml
      - components/wavin/channel_08.yaml
      - components/wavin/channel_09.yaml
      - components/wavin/channel_10.yaml
      - components/wavin/channel_11.yaml
#      - components/wavin/channel_12.yaml
      - components/wavin/channel_13.yaml
    refresh: 0s

uart:
  id: uart_${device}
  rx_pin: GPIO16
  tx_pin: GPIO17
  baud_rate: 38400
  stop_bits: 1
    
modbus:
  id: ${device}_modbus
  uart_id: uart_${device}

modbus_controller:
  id: ${device}_modbus_controller
  address: 1
  modbus_id: wavin_modbus
  update_interval: 5s    
    
