# This YAML snippet is for the Makerpad Pro 
substitutions:
  device: "strom-priser"
  name: "Strøm Priser"
  ssid: "Strom-Priser"
  version: "1.0"

#############################################
###            CORE SETTINGS              ###
#############################################

esphome:
  name: "${device}"
  friendly_name: "${name}"
  project:
    name: "briis.${device}"
    version: "${version}"
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.arduino.memory_type: qio_opi
    board_build.flash_mode: dio

esp32:
  board: esp-wrover-kit
  flash_size: 8MB
  framework:
    type: esp-idf

psram:
  mode: octal
  speed: 80MHz

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "lJzV5l7YROhqkmUY+YXRUCBkKGF0O8EG3IZJg0KG9OU="

ota:
  - platform: esphome
    password: "4e75bf7fd0e7cf3767417ac7352ba6fb"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${ssid} Hotspot"
    password: "12345678"

captive_portal:

#############################################
###          GENERAL SETTINGS             ###
#############################################
time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Copenhagen
    servers:
      - 77.33.79.202
      - 213.5.39.34
      - 162.159.200.123

#############################################
###               HARDWARE                ###
#############################################

spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12

i2c:
  sda: GPIO26
  scl: GPIO27
  scan: true
  frequency: 100kHz

display:
  - platform: ili9xxx
    model: ILI9488_A
    id: maindisp
    dc_pin: GPIO33
    cs_pin: GPIO15
    invert_colors: false
    color_order: bgr
    dimensions:
      height: 320
      width: 480
      offset_height: 0
      offset_width: 0
    rotation: 180
    show_test_card: true
    update_interval: 60s
    auto_clear_enabled: False

touchscreen:
  - platform: ft63x6
    id: ft6236touch
    display: maindisp
    address: 0x38
    # interrupt_pin: GPIO18
    on_touch:
      - lambda: |-
            ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
                touch.x,
                touch.y,
                touch.x_raw,
                touch.y_raw
                );


#############################################
###              TEXT SENSOR              ###
#############################################
text_sensor:
  - platform: wifi_info
    mac_address:
      name: "MAC Adresse"
      id: mac_address
      icon: mdi:information-slab-circle-outline
    ip_address:
      name: "IP Adresse"
      id: ip_address
      icon: mdi:ip-network
  - platform: template
    id: mac_str
    name: "MAC Adresse Text"
    internal: True
    update_interval: never
